// lib/cars.ts
// ─────────────────────────────────────────────────────────────────────────────
// SCHEMA REFERENCE (for future Convex table)
// Each car object maps 1-to-1 with what will become a Convex document.
// Fields marked [CONVEX] indicate the field name to use in the schema.
// Images will be stored as Convex Storage IDs in production.
// ─────────────────────────────────────────────────────────────────────────────

export type CarAvailability = "Buy" | "Rent" | "Both";
export type CarCondition = "New" | "Used";
export type FuelType = "Petrol" | "Diesel" | "Electric" | "Hybrid";
export type Transmission = "Automatic" | "Manual";

export interface Car {
  id: string; // [CONVEX] _id (auto-generated)
  name: string; // [CONVEX] name: v.string()
  brand: string; // [CONVEX] brand: v.string()
  model: string; // [CONVEX] model: v.string()
  year: number; // [CONVEX] year: v.number()
  type: string; // [CONVEX] type: v.string()  e.g. "SUV", "Sedan", "Sports"
  tags: string[]; // [CONVEX] tags: v.array(v.string())
  condition: CarCondition; // [CONVEX] condition: v.union(v.literal("New"), v.literal("Used"))
  available: CarAvailability; // [CONVEX] available: v.union(...)
  buyPrice: number | null; // [CONVEX] buyPrice: v.optional(v.number())
  rentPricePerDay: number | null; // [CONVEX] rentPricePerDay: v.optional(v.number())
  mileage: number; // [CONVEX] mileage: v.number()  (km)
  fuelType: FuelType; // [CONVEX] fuelType: v.string()
  transmission: Transmission; // [CONVEX] transmission: v.string()
  engineSize: string; // [CONVEX] engineSize: v.string()  e.g. "3.5L V6"
  horsepower: number; // [CONVEX] horsepower: v.number()
  torque: string; // [CONVEX] torque: v.string()  e.g. "450 Nm"
  topSpeed: string; // [CONVEX] topSpeed: v.string()
  acceleration: string; // [CONVEX] acceleration: v.string()  "0-100 km/h in Xs"
  seatingCapacity: number; // [CONVEX] seatingCapacity: v.number()
  doors: number; // [CONVEX] doors: v.number()
  color: string; // [CONVEX] color: v.string()
  fuelEfficiency: string; // [CONVEX] fuelEfficiency: v.string()  e.g. "10L/100km"
  features: string[]; // [CONVEX] features: v.array(v.string())
  images: string[]; // [CONVEX] images: v.array(v.id("_storage"))  → URLs in prod
  description: string; // [CONVEX] description: v.string()
}

export const cars: Car[] = [
  {
    id: "car-001",
    name: "BMW 5 Series",
    brand: "BMW",
    model: "530i",
    year: 2023,
    type: "Sedan",
    tags: ["Sedan", "Luxury", "Premium"],
    condition: "New",
    available: "Both",
    buyPrice: 28500000,
    rentPricePerDay: 65000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2.0L Turbo",
    horsepower: 248,
    torque: "350 Nm",
    topSpeed: "250 km/h",
    acceleration: "0-100 km/h in 6.1s",
    seatingCapacity: 5,
    doors: 4,
    color: "Alpine White",
    fuelEfficiency: "8.2L/100km",
    features: [
      "Sunroof",
      "Heated seats",
      "Parking sensors",
      "Reverse camera",
      "Apple CarPlay / Android Auto",
      "Adaptive cruise control",
      "Lane departure warning",
      "Wireless charging",
      "Ambient lighting",
      "BMW iDrive 8 infotainment",
    ],
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The BMW 5 Series combines executive comfort with driving dynamism. A perfect blend of luxury and performance for the modern professional.",
  },
  {
    id: "car-002",
    name: "Mercedes-Benz GLE",
    brand: "Mercedes-Benz",
    model: "GLE 450",
    year: 2023,
    type: "SUV",
    tags: ["SUV", "Luxury", "Premium", "Off-Road"],
    condition: "New",
    available: "Both",
    buyPrice: 52000000,
    rentPricePerDay: 95000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineSize: "3.0L Inline-6 Turbo",
    horsepower: 362,
    torque: "500 Nm",
    topSpeed: "250 km/h",
    acceleration: "0-100 km/h in 5.7s",
    seatingCapacity: 5,
    doors: 4,
    color: "Obsidian Black",
    fuelEfficiency: "7.4L/100km",
    features: [
      "MBUX infotainment",
      "Air suspension",
      "Burmester surround sound",
      "360° camera",
      "Heated & ventilated seats",
      "Ambient lighting (64 colors)",
      "Head-up display",
      "E-Active Body Control",
      "Wireless charging",
      "Night Vision Assist",
    ],
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The GLE is the definitive luxury SUV — spacious, powerful, and packed with Mercedes-Benz's latest technology.",
  },
  {
    id: "car-003",
    name: "Toyota Land Cruiser",
    brand: "Toyota",
    model: "Land Cruiser 300",
    year: 2022,
    type: "SUV",
    tags: ["SUV", "Off-Road", "Family"],
    condition: "Used",
    available: "Buy",
    buyPrice: 38000000,
    rentPricePerDay: null,
    mileage: 22000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineSize: "3.3L Twin-Turbo V6 Diesel",
    horsepower: 309,
    torque: "700 Nm",
    topSpeed: "210 km/h",
    acceleration: "0-100 km/h in 8.4s",
    seatingCapacity: 7,
    doors: 4,
    color: "Midnight Black",
    fuelEfficiency: "9.5L/100km",
    features: [
      "Multi-Terrain Select",
      "Crawl Control",
      "KDSS suspension",
      "14-inch touchscreen",
      "JBL Premium Audio",
      "Panoramic sunroof",
      "Power running boards",
      "Digital rear-view mirror",
      "4WD",
      "Toyota Safety Sense",
    ],
    images: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "A legendary off-road icon — the Land Cruiser 300 tackles any terrain while delivering genuine luxury inside.",
  },
  {
    id: "car-004",
    name: "Porsche 911 Carrera",
    brand: "Porsche",
    model: "911 Carrera S",
    year: 2023,
    type: "Sports",
    tags: ["Sports", "Performance", "Luxury", "Premium"],
    condition: "New",
    available: "Rent",
    buyPrice: null,
    rentPricePerDay: 180000,
    mileage: 800,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3.0L Twin-Turbo Flat-6",
    horsepower: 450,
    torque: "530 Nm",
    topSpeed: "308 km/h",
    acceleration: "0-100 km/h in 3.5s",
    seatingCapacity: 4,
    doors: 2,
    color: "Guards Red",
    fuelEfficiency: "10.6L/100km",
    features: [
      "Sport Chrono Package",
      "PASM sport suspension",
      "Sport exhaust",
      "Bose Surround Sound",
      "Porsche Communication Management",
      "Lane Change Assist",
      "Adaptive cruise control",
      "Carbon ceramic brakes",
      "Rear-axle steering",
      "Night Vision Assist",
    ],
    images: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611821064430-0d40291d0f0b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582467029786-c5d8d8e0f6a6?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Porsche 911 Carrera S is the benchmark sports car — an intoxicating blend of heritage, precision and raw performance.",
  },
  {
    id: "car-005",
    name: "Tesla Model 3",
    brand: "Tesla",
    model: "Model 3 Long Range",
    year: 2023,
    type: "Sedan",
    tags: ["Sedan", "Electric", "Performance"],
    condition: "New",
    available: "Both",
    buyPrice: 22000000,
    rentPricePerDay: 45000,
    mileage: 0,
    fuelType: "Electric",
    transmission: "Automatic",
    engineSize: "Dual Motor AWD",
    horsepower: 358,
    torque: "493 Nm",
    topSpeed: "233 km/h",
    acceleration: "0-100 km/h in 4.4s",
    seatingCapacity: 5,
    doors: 4,
    color: "Pearl White Multi-Coat",
    fuelEfficiency: "15.7 kWh/100km",
    features: [
      "Autopilot",
      "Full Self-Driving capability",
      '15.4" touchscreen',
      "Over-the-air updates",
      "Sentry Mode",
      "Dog Mode",
      "Premium audio",
      "Glass roof",
      "Wireless charging",
      "360km+ range",
    ],
    images: [
      "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "Tesla's most popular model — a high-tech electric sedan that accelerates like a sports car and charges in minutes.",
  },
  {
    id: "car-006",
    name: "Range Rover Sport",
    brand: "Land Rover",
    model: "Range Rover Sport HSE",
    year: 2022,
    type: "SUV",
    tags: ["SUV", "Luxury", "Off-Road", "Premium"],
    condition: "Used",
    available: "Both",
    buyPrice: 42000000,
    rentPricePerDay: 85000,
    mileage: 18000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3.0L Ingenium Turbo",
    horsepower: 395,
    torque: "550 Nm",
    topSpeed: "250 km/h",
    acceleration: "0-100 km/h in 5.8s",
    seatingCapacity: 5,
    doors: 4,
    color: "Santorini Black",
    fuelEfficiency: "11.2L/100km",
    features: [
      "Terrain Response 2",
      "Air suspension",
      "Pivi Pro infotainment",
      "Meridian Signature Sound",
      "Interactive Driver Display",
      "Wade sensing",
      "Pixel LED headlights",
      "Heated/cooled seats",
      "Panoramic sunroof",
      "ClearSight Ground View",
    ],
    images: [
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Range Rover Sport defines the luxury performance SUV segment — commanding presence, outstanding capability.",
  },
  {
    id: "car-007",
    name: "Toyota Camry",
    brand: "Toyota",
    model: "Camry XSE V6",
    year: 2022,
    type: "Sedan",
    tags: ["Sedan", "Family"],
    condition: "Used",
    available: "Buy",
    buyPrice: 12500000,
    rentPricePerDay: null,
    mileage: 35000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3.5L V6",
    horsepower: 301,
    torque: "362 Nm",
    topSpeed: "210 km/h",
    acceleration: "0-100 km/h in 5.8s",
    seatingCapacity: 5,
    doors: 4,
    color: "Midnight Black Metallic",
    fuelEfficiency: "9.1L/100km",
    features: [
      "Apple CarPlay / Android Auto",
      "Wireless charging",
      "JBL audio",
      "Blind spot monitor",
      "Rear cross traffic alert",
      "Pre-collision system",
      "Dynamic radar cruise control",
      "Panoramic moonroof",
      "Ventilated front seats",
      '8" touchscreen',
    ],
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Camry XSE V6 is the sporty face of Toyota's best-selling sedan — powerful, reliable, and surprisingly fun to drive.",
  },
  {
    id: "car-008",
    name: "Lamborghini Urus",
    brand: "Lamborghini",
    model: "Urus S",
    year: 2023,
    type: "SUV",
    tags: ["SUV", "Performance", "Luxury", "Premium", "Sports"],
    condition: "New",
    available: "Rent",
    buyPrice: null,
    rentPricePerDay: 350000,
    mileage: 200,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4.0L Twin-Turbo V8",
    horsepower: 666,
    torque: "850 Nm",
    topSpeed: "306 km/h",
    acceleration: "0-100 km/h in 3.5s",
    seatingCapacity: 5,
    doors: 4,
    color: "Giallo Auge",
    fuelEfficiency: "13.5L/100km",
    features: [
      "Lamborghini Dinamica Veicolo Integrata",
      "Carbon ceramic brakes",
      "Adaptive air suspension",
      "Bang & Olufsen 3D Advanced Sound System",
      "Alcantara/leather interior",
      "Rear steering",
      "Night Vision",
      "Head-up display",
      "Off-road mode",
      "Torque Vectoring Plus",
    ],
    images: [
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Urus S is the world's first Super Sport Utility Vehicle — supercar DNA wrapped in a practical, devastatingly quick SUV.",
  },
  {
    id: "car-009",
    name: "Honda Accord",
    brand: "Honda",
    model: "Accord Sport 2.0T",
    year: 2021,
    type: "Sedan",
    tags: ["Sedan", "Family"],
    condition: "Used",
    available: "Both",
    buyPrice: 9800000,
    rentPricePerDay: 22000,
    mileage: 48000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2.0L Turbo",
    horsepower: 192,
    torque: "260 Nm",
    topSpeed: "195 km/h",
    acceleration: "0-100 km/h in 7.9s",
    seatingCapacity: 5,
    doors: 4,
    color: "Sonic Gray Pearl",
    fuelEfficiency: "8.7L/100km",
    features: [
      "Honda Sensing suite",
      "Apple CarPlay / Android Auto",
      '8" touchscreen',
      "Wireless charging",
      "Heated front seats",
      "Remote start",
      "LED headlights",
      "Adaptive cruise control",
      "Lane keeping assist",
      "10-way power driver seat",
    ],
    images: [
      "https://images.unsplash.com/photo-1617531653332-bd46c16f7d5a?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Accord Sport strikes the ideal balance between everyday practicality and engaging driving dynamics.",
  },
  {
    id: "car-010",
    name: "Ferrari SF90 Stradale",
    brand: "Ferrari",
    model: "SF90 Stradale",
    year: 2023,
    type: "Sports",
    tags: ["Sports", "Performance", "Luxury", "Premium"],
    condition: "New",
    available: "Rent",
    buyPrice: null,
    rentPricePerDay: 550000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineSize: "4.0L Twin-Turbo V8 + 3 Electric Motors",
    horsepower: 986,
    torque: "800 Nm",
    topSpeed: "340 km/h",
    acceleration: "0-100 km/h in 2.5s",
    seatingCapacity: 2,
    doors: 2,
    color: "Rosso Corsa",
    fuelEfficiency: "8.0L/100km (combined)",
    features: [
      "Full electric mode (EV)",
      "eManettino driving modes",
      "Side Slip Control 6.1",
      "Carbon fibre bodywork",
      "Active aerodynamics",
      "Head-up display",
      '16" curved instrument cluster',
      "Fiorano handling package",
      "Assetto Fiorano upgrade kit",
      "Carbon-ceramic ABS brakes",
    ],
    images: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "Ferrari's most powerful road car ever made — a plug-in hybrid hypercar with almost 1000hp and screaming performance.",
  },
  {
    id: "car-011",
    name: "Lexus RX 500h",
    brand: "Lexus",
    model: "RX 500h F Sport",
    year: 2023,
    type: "SUV",
    tags: ["SUV", "Luxury", "Hybrid"],
    condition: "New",
    available: "Both",
    buyPrice: 34000000,
    rentPricePerDay: 72000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineSize: "2.4L Turbo Hybrid",
    horsepower: 366,
    torque: "550 Nm",
    topSpeed: "200 km/h",
    acceleration: "0-100 km/h in 6.0s",
    seatingCapacity: 5,
    doors: 4,
    color: "Sonic Titanium",
    fuelEfficiency: "6.7L/100km",
    features: [
      "Mark Levinson 21-speaker audio",
      '14" touchscreen',
      "Head-up display",
      "Panoramic sunroof",
      "Lexus Safety System+",
      "Digital side mirrors",
      "Adaptive variable suspension",
      "Heated/ventilated seats",
      "Wireless charging",
      "Remote Park Assist",
    ],
    images: [
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The RX 500h F Sport combines Lexus luxury with hybrid efficiency and sharp F Sport performance tuning.",
  },
  {
    id: "car-012",
    name: "Ford Bronco",
    brand: "Ford",
    model: "Bronco Wildtrak",
    year: 2022,
    type: "SUV",
    tags: ["SUV", "Off-Road", "Family"],
    condition: "Used",
    available: "Both",
    buyPrice: 14500000,
    rentPricePerDay: 35000,
    mileage: 27000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2.7L EcoBoost V6",
    horsepower: 330,
    torque: "542 Nm",
    topSpeed: "190 km/h",
    acceleration: "0-100 km/h in 7.0s",
    seatingCapacity: 5,
    doors: 4,
    color: "Cactus Gray",
    fuelEfficiency: "11.8L/100km",
    features: [
      "G.O.A.T. Modes",
      "Sasquatch Package 4x4",
      "Removable doors",
      "Removable roof",
      '12" SYNC 4 touchscreen',
      "Trail Turn Assist",
      "Trail Control",
      "Front & rear locking differentials",
      "Rock-Crawl mode",
      "Outer Banks bumpers",
    ],
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "Built for adventure — the Bronco Wildtrak brings back the iconic nameplate with serious off-road capability.",
  },
  {
    id: "car-013",
    name: "Audi A6",
    brand: "Audi",
    model: "A6 55 TFSI quattro",
    year: 2022,
    type: "Sedan",
    tags: ["Sedan", "Luxury", "Premium"],
    condition: "Used",
    available: "Both",
    buyPrice: 23500000,
    rentPricePerDay: 55000,
    mileage: 31000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "3.0L TFSI V6",
    horsepower: 335,
    torque: "500 Nm",
    topSpeed: "250 km/h",
    acceleration: "0-100 km/h in 5.1s",
    seatingCapacity: 5,
    doors: 4,
    color: "Navarra Blue Metallic",
    fuelEfficiency: "8.9L/100km",
    features: [
      "Audi Virtual Cockpit Plus",
      "MMI Navigation Plus",
      "Bang & Olufsen 3D Sound",
      "Heads-up display",
      "Adaptive air suspension",
      "quattro AWD",
      "Audi pre sense 360",
      "Matrix LED headlights",
      "Wireless charging",
      "Heated/ventilated front seats",
    ],
    images: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The A6 55 TFSI quattro delivers effortless performance with Audi's signature understated elegance and cutting-edge tech.",
  },
  {
    id: "car-014",
    name: "Chevrolet Corvette",
    brand: "Chevrolet",
    model: "Corvette Stingray Z51",
    year: 2023,
    type: "Sports",
    tags: ["Sports", "Performance"],
    condition: "New",
    available: "Rent",
    buyPrice: null,
    rentPricePerDay: 220000,
    mileage: 500,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "6.2L LT2 V8",
    horsepower: 495,
    torque: "637 Nm",
    topSpeed: "312 km/h",
    acceleration: "0-100 km/h in 2.9s",
    seatingCapacity: 2,
    doors: 2,
    color: "Torch Red",
    fuelEfficiency: "12.4L/100km",
    features: [
      "Z51 Performance Package",
      "Electronic Limited Slip Differential",
      "Magnetic Ride Control",
      "Front lift system",
      "Performance data recorder",
      "Head-up display",
      "Bose Performance Series audio",
      "GT2 seats",
      "Carbon Flash accents",
      "Competitive Mode",
    ],
    images: [
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "America's sports car in its most capable form — the mid-engine Corvette Z51 rewrites what an American performance car can be.",
  },
  {
    id: "car-015",
    name: "Volkswagen Tiguan",
    brand: "Volkswagen",
    model: "Tiguan R-Line",
    year: 2022,
    type: "SUV",
    tags: ["SUV", "Family"],
    condition: "Used",
    available: "Both",
    buyPrice: 11200000,
    rentPricePerDay: 28000,
    mileage: 41000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "2.0L TSI Turbo",
    horsepower: 184,
    torque: "320 Nm",
    topSpeed: "210 km/h",
    acceleration: "0-100 km/h in 7.5s",
    seatingCapacity: 7,
    doors: 4,
    color: "Deep Black Pearl",
    fuelEfficiency: "8.1L/100km",
    features: [
      "IQ.DRIVE safety suite",
      "Digital Cockpit Pro",
      "Discover Pro navigation",
      "3-zone climate control",
      "Panoramic sunroof",
      "4MOTION AWD",
      "Park Distance Control",
      "Rear-view camera",
      "Wireless charging",
      "Third-row seating",
    ],
    images: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Tiguan R-Line offers European sophistication and a 7-seat layout — practical family transport with genuine style.",
  },
  {
    id: "car-016",
    name: "McLaren 720S",
    brand: "McLaren",
    model: "720S Performance",
    year: 2022,
    type: "Sports",
    tags: ["Sports", "Performance", "Luxury"],
    condition: "Used",
    available: "Rent",
    buyPrice: null,
    rentPricePerDay: 480000,
    mileage: 8000,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "4.0L Twin-Turbo V8",
    horsepower: 710,
    torque: "770 Nm",
    topSpeed: "341 km/h",
    acceleration: "0-100 km/h in 2.9s",
    seatingCapacity: 2,
    doors: 2,
    color: "Papaya Spark",
    fuelEfficiency: "12.8L/100km",
    features: [
      "Proactive Chassis Control II",
      "Variable Drift Control",
      "Folding Driver Display",
      "McLaren Track Telemetry",
      "Carbon Fibre MonoCell II-T",
      "Electrochromic roof",
      "Bowers & Wilkins audio",
      "Active dynamics panel",
      "Nose lift system",
      "Track mode",
    ],
    images: [
      "https://images.unsplash.com/photo-1611821064430-0d40291d0f0b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The 720S is McLaren's purest expression of supercar philosophy — breathtaking speed paired with everyday usability.",
  },
  {
    id: "car-017",
    name: "Hyundai Tucson",
    brand: "Hyundai",
    model: "Tucson N Line",
    year: 2023,
    type: "SUV",
    tags: ["SUV", "Family"],
    condition: "New",
    available: "Both",
    buyPrice: 8900000,
    rentPricePerDay: 20000,
    mileage: 0,
    fuelType: "Hybrid",
    transmission: "Automatic",
    engineSize: "1.6L Turbo Hybrid",
    horsepower: 230,
    torque: "350 Nm",
    topSpeed: "185 km/h",
    acceleration: "0-100 km/h in 8.1s",
    seatingCapacity: 5,
    doors: 4,
    color: "Amazon Gray",
    fuelEfficiency: "5.7L/100km",
    features: [
      '10.25" touchscreen',
      "Hyundai SmartSense",
      "Blind-spot collision avoidance",
      "Surround View Monitor",
      "Panoramic sunroof",
      "Heated/ventilated front seats",
      "Wireless charging",
      "Remote start",
      "Highway Drive Assist",
      "Bose Premium Audio",
    ],
    images: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Tucson N Line redefines what a compact SUV can be — striking design, hybrid efficiency, and a long list of tech.",
  },
  {
    id: "car-018",
    name: "Rolls-Royce Ghost",
    brand: "Rolls-Royce",
    model: "Ghost Extended",
    year: 2023,
    type: "Sedan",
    tags: ["Sedan", "Luxury", "Premium"],
    condition: "New",
    available: "Rent",
    buyPrice: null,
    rentPricePerDay: 750000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "6.75L Twin-Turbo V12",
    horsepower: 563,
    torque: "850 Nm",
    topSpeed: "250 km/h",
    acceleration: "0-100 km/h in 4.8s",
    seatingCapacity: 5,
    doors: 4,
    color: "Andalusian White",
    fuelEfficiency: "14.5L/100km",
    features: [
      "Starlight Headliner (1,344 LEDs)",
      "Bespoke Audio system",
      "Flagged self-closing doors",
      "Illuminated fascia",
      "Planar suspension",
      "Night Vision",
      "Heated/cooled/massaging rear seats",
      "Champagne cooler",
      "Rear theatre screen",
      "Air Purification System",
    ],
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Ghost Extended is the pinnacle of automotive luxury — hand-crafted perfection from the House of Rolls-Royce.",
  },
  {
    id: "car-019",
    name: "Jeep Wrangler",
    brand: "Jeep",
    model: "Wrangler Unlimited Rubicon",
    year: 2022,
    type: "SUV",
    tags: ["SUV", "Off-Road"],
    condition: "Used",
    available: "Both",
    buyPrice: 16800000,
    rentPricePerDay: 38000,
    mileage: 29000,
    fuelType: "Petrol",
    transmission: "Manual",
    engineSize: "3.6L Pentastar V6",
    horsepower: 285,
    torque: "347 Nm",
    topSpeed: "175 km/h",
    acceleration: "0-100 km/h in 8.5s",
    seatingCapacity: 5,
    doors: 4,
    color: "Sting-Gray",
    fuelEfficiency: "12.6L/100km",
    features: [
      "Rock-Trac 4WD",
      "Tru-Lok front & rear lockers",
      "Sway bar disconnect",
      'Uconnect 4C Nav 8.4"',
      "Trail Rated badge",
      "Skid plates",
      "LED headlights",
      "Removable doors & roof",
      "Off-Road Plus mode",
      "Apple CarPlay",
    ],
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Wrangler Rubicon is an off-road legend — unstoppable on any terrain, unmistakable on any road.",
  },
  {
    id: "car-020",
    name: "Bentley Bentayga",
    brand: "Bentley",
    model: "Bentayga Speed",
    year: 2023,
    type: "SUV",
    tags: ["SUV", "Luxury", "Performance", "Premium"],
    condition: "New",
    available: "Both",
    buyPrice: 95000000,
    rentPricePerDay: 420000,
    mileage: 0,
    fuelType: "Petrol",
    transmission: "Automatic",
    engineSize: "6.0L Twin-Turbo W12",
    horsepower: 635,
    torque: "900 Nm",
    topSpeed: "306 km/h",
    acceleration: "0-100 km/h in 3.9s",
    seatingCapacity: 5,
    doors: 4,
    color: "Glacier White",
    fuelEfficiency: "14.8L/100km",
    features: [
      "Bentley Dynamic Ride",
      "Rotating Display (3 faces)",
      "Naim for Bentley 1,950W audio",
      "Air suspension",
      "Night Vision",
      "Rear-seat entertainment",
      "Massaging/heating/cooling seats",
      "Mood lighting",
      "Head-up display",
      "Bentley On-Board Wi-Fi",
    ],
    images: [
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80&auto=format&fit=crop",
    ],
    description:
      "The Bentayga Speed is the fastest SUV Bentley has ever made — combining blistering W12 performance with unrivalled cabin luxury.",
  },
];

// ─── Derived filter data ───────────────────────────────────────────────────────

export const allBrands = [
  "All Brands",
  ...Array.from(new Set(cars.map((c) => c.brand))).sort(),
];

const baseTypes = ["All", "Sedan", "SUV", "Sports"];
const extraTags = [
  "Luxury",
  "Performance",
  "Off-Road",
  "Family",
  "Premium",
  "Electric",
  "Used Car",
];
export const allTags = [...baseTypes, ...extraTags];
